version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app'
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npm start"
    user: "1000:1000"
    depends_on:
      - database
  database:
    container_name: mysql-database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'desafio-backend'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
