version: '3.5'

services:
  database:
    container_name: mysql-database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'desafio-backend'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
