name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-tests-audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Instalar Dependências
      run: npm install

    - name: Executar Testes Unitários
      run: npm test

    - name: Executar Cobertura de Testes
      run: npm run test:coverage

    - name: Build da Aplicação
      run: npm run build

    - name: Executar npm audit
      run: npm audit

    - name: CodeClimate Scan
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code $?
