name: Node.js CI

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Executar Testes Unitários
      run: npm test

    - name: Executar Cobertura de Testes
      run: npm run test:coverage

  install-dependencies:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    needs: unit-tests
=======
>>>>>>> 48fde8185e83eb366cc78f269c661d5cbbe8f995

    steps:
      - name: Limpar cache do npm
        run: npm cache clean --force

      - name: Instalar Dependências
        run: npm install
      
      - name: Gerar arquivo package-lock.json
        run: npm i --package-lock-only
    
  build-application:
<<<<<<< HEAD
    runs-on: ubuntu-latest
    needs: install-dependencies
=======
    needs: install-dependencies
    runs-on: ubuntu-latest
>>>>>>> 48fde8185e83eb366cc78f269c661d5cbbe8f995

    steps:
      - name: Build da Aplicação
        run: npm run build
  
  check-vulnerabilities:
<<<<<<< HEAD
=======
    needs: unit-tests
>>>>>>> 48fde8185e83eb366cc78f269c661d5cbbe8f995
    runs-on: ubuntu-latest
    needs: build-application

    steps:
      - name: Executar npm audit
        run: npm audit
